### PR TITLE
Force correct type in operator methods

### PR DESCRIPTION
**Pull request by jkwashbourne**

### CODE REVIEW

**Review by samtkaplan — CHANGES_REQUESTED** [review]
Thanks!

1. Let's remove the '2'... So, `AbstractArray{Float32}` instead.  Since the '2' doesn't address the problem that you are trying to solve.  In addition, you should only need this change for the reference model, right?

2. There appear to be left-over debug statements?  (`@show` methods).

**Comment by samtkaplan** [comment]
I would prefer to only address the issue at hand.  I'm worried about introducing other unexpected issues.

**Comment by jkwashbourne** [comment]
OK, I removed from data args, and rebased.

**Comment by jkwashbourne** [comment]
and now removed the leftover @show

**Review by samtkaplan — APPROVED** [review]

**Pull request merged**
