### PR TITLE
move SpecialFunctions in Project.toml and rationalize tests for ops

### PR DESCRIPTION
**Pull request by jkwashbourne**

### CODE REVIEW

**Review by samtkaplan — CHANGES_REQUESTED** [review]
Thanks!  I think there is an not-intended change in "runtests.jl".

**Comment by jkwashbourne** [comment]
Removed the random seed.

**Review by samtkaplan — CHANGES_REQUESTED** [review]
Looks good.  Can you squash the two commits into one, please.

**Comment by jkwashbourne** [comment]
> Looks good. Can you squash the two commits into one, please.

done

**Review by samtkaplan — APPROVED** [review]

**Pull request merged**
