### PR TITLE
use Formatting.jl for logging

### PR DESCRIPTION
**Pull request by samtkaplan**
The primary motivation for this change is to make `@code_warntype` and friends easier to interpret.  In particular, `@sprintf` seems to generate some "red" output from `@code_warntype`.  As a side-note, I do think that this also makes the code slightly easier to read.

### CODE REVIEW

**Comment by jkwashbourne** [comment]
im worried about perf impact of this, but that is just a knee jerk reaction. this isnt being called very often.

**Comment by jkwashbourne** [comment]
I think we may need some tests to run longer/bigger jobs and report timing. I guess the micro benchmarks in WaveFD handle the propagator performance, but I am thinking about the overall operators.

**Comment by samtkaplan** [comment]
I'm thinking that https://github.com/ChevronETC/JetPackWaveFD.jl/pull/12 should help with your concern.  Funny enough, this change is motivated by performance issues.  I saw that the use of @sprintf was making it harder to read the output of `@code_warntype`, and switching from **Printf** to **Formatting** made it easier to see any relevant type stability issues.

**Comment by samtkaplan** [comment]
@jkwashbourne Here is the type instability that crept into the code when using @sprintf:
image
To be honest, I don't think this is such a big deal since my understanding is that Julia does well at handling small unions of types.  But, in general not having this is in the code does make it easier to search for type instabilities.

**Review by jkwashbourne — APPROVED** [review]

**Pull request merged**
